### ISSUE TITLE
Migrate core of GOA to IRIS

### ISSUE THREAD

**Issue by vpino** [merakiVE/CEHDUN#1]
**Comportamiento Actual** 

En este momento el core esta desarrollado con la tecnologia GOA la cual presenta ciertas limitantes:

* Complejidad de respuestas y entrada de datos de los endpoints.
* Escribir mas codigo.
* Carencia de edicion para un endpoint que requiera cambios unicos y especiales.
* Utilizando GOA en el core se rompe el standar de utilizar las mismas tecnologias en los diferentes componentes de MerakiVE.
* Mayor curba de aprendizaje.

**Comportamiento Esperado**
 
*  Endpoints faciles de configurar y adaptar.
*  Generar menos codigo, aumentar productividad.
*  Estandarizar las tecnologias.
*  Curva de aprendizaje flexible para nuevos desarrolladores.

**Reproducción del Problema**

**Comment by hostelix** [comment]
Ya se realizo la migracion
